### ISSUE TITLE
NPC's wrong faction

### ISSUE THREAD

**Issue by gbmv33** [azerothcore/mod-guildhouse#1]
- The npc Guild House Seller, does not come with faction 35

- The NPC that appears as you type .guildhouse spawnnpc, does not come with faction 35

**Comment by BarbzYHOOL** [comment]
@gbmv33 hey this is the occasion to fix it, it's very easy!

https://github.com/azerothcore/mod-guildhouse/tree/master/sql/world

Look it's in one of these files. They can be improved + fixed
