### ISSUE TITLE
error compile

### ISSUE THREAD

**Issue by dev-master21** [azerothcore/mod-guildhouse#10]
![image](https://user-images.githubusercontent.com/16816228/74190187-2514d780-4c7c-11ea-9a0a-a275cc334e9a.png)

Last Rev AC

**Comment by BarbzYHOOL** [comment]
try to remove these parameters from the code?

**Comment by BarbzYHOOL** [comment]
also try this Pull Request https://github.com/azerothcore/mod-guildhouse/pull/8

**Comment by dev-master21** [comment]
> try to remove these parameters from the code?

yes. New bugs appear

**Comment by dev-master21** [comment]
> also try this Pull Request #8

That helped. thanks

**Comment by BarbzYHOOL** [comment]
@dev-master21 can you comment after testing all the changes ? comment on this page https://github.com/azerothcore/mod-guildhouse/pull/8
