### ISSUE TITLE
Bug with phases (wintergrasp, .gm off etc)

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-guildhouse#12]
There are bugs with phases in the outer world (Wintergrasp, using .gm off etc...)

Explanation by Stoabrogga:

> each creature/gameobject has a phasemask... which is just a bit mask combining the phases in which the creature is visible, e.g. phase 1 = 1, 2 = 2, 3 = 4, 4 = 8, 5 = 16 etc... so a creature which should be visible in phases 2 and 4 would use phasemask 2+8 = 10. You can modify your phase as GM using the command "modify phase". If you use "gm on" you automatically set your own phasemask to "PHASEMASK_ANYWHERE" (0xFFFFFFFF), so you see all phases together. For a player the phases are managed via specific auras, e.g. spell 59062 which forces the player to only see phase 7 (bit 64). This is normally handled via table "spell_area". What the patch for the guild house does is remove the ability to combine phases for area 876 (GM Island), because this would only allow 32 phases, and instead use the phasemask as actual value, which means phase 1 = 1, 2 = 2, 3 = 3, 4 = 4, 5 = 5 etc., so you potentially get 4294967295 different phases there. Concerning the bug: After leaving the guildhouse only the first phase is restored to the player, but he could have more than one phase by his auras.

Refer to this [comment](
https://github.com/azerothcore/mod-guildhouse/pull/6#issuecomment-539960023) (after PR #8 has been merged) if you want to try a solution:

**Comment by Stoabrogga** [comment]
Should be fixed with commit 0d987d1.
