### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by dev-master21** [azerothcore/mod-guildhouse#15]
after type in chat .guildhouse spawnnpc - server crushed

**Comment by BarbzYHOOL** [comment]
i didn't even know this command existed, maybe it's not implemented correctly

**Comment by dev-master21** [comment]
> я даже не знал, что эта команда существует, возможно, она не реализована правильно

Try using it without a guild. It seems to me that due to the fact that a player without a guild, the server shuts down

**Comment by Stoabrogga** [comment]
The error is caused by this:
https://github.com/azerothcore/mod-guildhouse/blob/db18f95282924efc62a990696aeec9287e355285/src/mod_guild_house_v2.cpp#L583
needs to be
```cpp
if (player->GetGuild() && player->GetGuild()->GetLeaderGUID() != player->GetGUID()) {
```

**Comment by BarbzYHOOL** [comment]
@dev-master21 will you test this https://github.com/azerothcore/mod-guildhouse/pull/14 or will you wait for us to do all the work??
