### ISSUE TITLE
Server Crash on loading Corpses

### ISSUE THREAD

**Issue by arthaswow** [azerothcore/mod-guildhouse#16]
If this module is installed and for some reason a restart is needed, if the table acore_characters.corpse have any data with field CorpseType 1 or 2 a error occurs and server wont start, needing a cleanup on this table.
the error:
**azerothcore/src/server/game/Entities/Object/Object.cpp:2099 in GetBaseMap ASSERTION FAILED:
  m_currMap**

HOW TO REPRODUCE

- 

1. Install and activate the module
2. Create a guild ingame .guild create nick "guildname"
3. Buy a GuildHouse
.4 Go to Telamortes Npc and click Teleport to Guildhouse
5. Inside GuildHouse in GM Island just die, .die or any another way
6. Click Release 
7. When relesead in ghost form restart the server
8. Startup the server again if no auto-restarter is presente and see the dump on Loading Corpses, the server wont start again ever

Cleaning the corpse table or changing all corpseType to 0 fix the problem and server will start again
Confirmed by removing the module from compile process and starting-up with full corpse populate table.

**Comment by hlainin** [comment]
I confirm the problem. The problem exists on the latest version of the server.

**Comment by arthaswow** [comment]
> I confirm the problem. The problem exists on the latest version of the server.

I found that it happens because the server tries to put the corpse in the map before loading the map...
but i dont understand why this behavior only happens with the module instaled..
i removed the corpse loading from server start and problem fixed, but all dead will be alive after restart xD

**Comment by hlainin** [comment]
> > I confirm the problem. The problem exists on the latest version of the server.
> 
> I found that it happens because the server tries to put the corpse in the map before loading the map...
> but i dont understand why this behavior only happens with the module instaled..
> i removed the corpse loading from server start and problem fixed, but all dead will be alive after restart xD

Can you show a piece of code where you made the changes?

**Comment by arthaswow** [comment]
File
\src\server\game\World\World.cpp
line : 1732
`sObjectMgr->LoadCorpses();`
just comment-out by
`//sObjectMgr->LoadCorpses();`

Remember, if the server crashes and auto-reboot all players will spawn ALIVE above the corpse xD
but no more map assert

**Comment by porkserver** [comment]
This does not occur on the current build of AC with PR #30
![Screen Shot 2022-03-28 at 12 40 35 PM](https://user-images.githubusercontent.com/273302/160455837-933b7339-a4b4-4794-bbf6-978d1a315c82.png)
