### ISSUE TITLE
Fails on Building

### ISSUE THREAD

**Issue by PsYchoNauTek** [azerothcore/mod-guildhouse#22]
Module gives multiple errors on building the latest branch of azerothcore.
[https://github.com/azerothcore/azerothcore-wotlk/commit/982be6de008181d7deb75cd8060c13e165a0a4e6](url)
![image](https://user-images.githubusercontent.com/95944184/154824330-f1d485ad-e87f-49f3-8a34-accc0a2e35af.png)

**Comment by porkserver** [comment]
I am also getting the PQuery error and MapMAnager.h error.  After a bit of poking files, I noticed the file in my AC/src/Maps folder was MapMgr.h I switched it to that in the cpp files and changed PQuery to Query...

`/home/gwilkins/azcorebuild/modules/mod-guildhouse/src/mod_guild_house_npc.cpp:253:44: fatal error: no member named 'PQuery' in 'DatabaseWorkerPool<WorldDatabaseConnection>'; did you mean 'Query'?
        QueryResult result = WorldDatabase.PQuery("SELECT `posX`, `posY`, `posZ`, `orientation` FROM `guild_house_spawns` WHERE `entry` = %u", entry);
                                           ^~~~~~
                                           Query
/home/gwilkins/azcorebuild/src/server/database/Database/DatabaseWorkerPool.h:119:17: note: 'Query' declared here
    QueryResult Query(std::string_view sql, Args&&... args)
                ^
1 error generated.
/home/gwilkins/azcorebuild/modules/mod-guildhouse/src/mod_guild_house_v2.cpp:15:10: fatal error: 'Maps/MapManager.h' file not found
#include "Maps/MapManager.h"
         ^~~~~~~~~~~~~~~~~~~
`
I got a whole different set of errors.

`/home/gwilkins/azcorebuild/modules/mod-guildhouse/src/mod_guild_house_v2.cpp:48:19: fatal error: no member named 'outBasic' in 'Log'
            sLog->outBasic("GUILDHOUSE: Deleting guild house data due to disbanding of guild...");
            ~~~~  ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:173: modules/CMakeFiles/modules.dir/mod-guildhouse/src/mod_guild_house_v2.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/gwilkins/azcorebuild/modules/mod-guildhouse/src/mod_guild_house_npc.cpp:261:30: fatal error: no member named 'GetFloat' in 'Field'
            posX = fields[0].GetFloat();
                   ~~~~~~~~~ ^`

That was a shot in the dark,  any thoughts?

**Comment by PsYchoNauTek** [comment]
Even after the changes of the Module from March the 4th it still is failing on build with exact the same errors which I already posted. =(

**Comment by porkserver** [comment]
PR #30 Fixes the Mod
