### ISSUE TITLE
Buying a guildhouse

### ISSUE THREAD

**Issue by Tiburan** [azerothcore/mod-guildhouse#4]
Where to buy a guildhouse?

.guildhouse SpawnNpc results in incorrect syntax, no Npc gets spawned.

**Comment by talamortis** [comment]
you will have to be in the zone for the code to work correctly.

**Comment by Tiburan** [comment]
Call me crazy, what zone are you referring to? 
I get the same syntax error on Gmisland, I take it this is the zone where the guildhouses are phased?

**Comment by talamortis** [comment]
Yeah it should work on gm island. Maybe because the core has updated the mapping ect it might of broken the code. I no longer contribute to the Azerothcore source. so i am unable to provide more assistance. Sorry

**Comment by Tiburan** [comment]
Thanks a bunch for your time anyway :) 
Let's hope someone else can also pitch in ^^

**Comment by Stoabrogga** [comment]
You have to spawn the Guild House Seller as GM using these commands:
`.npc add 70101` (permanently)
or
`.npc add temp 70101` (temporarily)

The command `.guildhouse spawnnpc` only spawns the Guild House Assistant (ID 70102) in the case he got lost somehow. The command only works on GM Island.
