### ISSUE TITLE
Bug: Error while inserting data/sql

### ISSUE THREAD

**Issue by Skiddoh** [azerothcore/mod-guildhouse#48]
### Current Behaviour

While executing the sqls the column modelid1 couldn't be found.

### Expected Behaviour

just execute sqls without error.

### Steps to reproduce the problem

- freshly install of AzerothCore
- adding the module to modules folder
- compiling
- starting the server → error

### Extra Notes

to fix this issue on my end, i simply removed the column from the insert statement. For me it looks like that the table creature_template does not have a column named modelid1 or modelid2 or modelid3 or modelid4.
Afterwards it showed me an error that there is no displayid for that creature, so i manually added the one from the initial sql query by using the following code:

```
INSERT INTO creature_template_model (CreatureID, IDX, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(500030,0,25901,1,1,1)

INSERT INTO creature_template_model (CreatureID, IDX, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(500031,0,25901,1,1,1)

INSERT INTO creature_template_model (CreatureID, IDX, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(500032,0,18234,1,1,1)
```

### AC rev. hash/commit

fb4dbdd60491

### Operating system

Debian 10 x64

### Custom changes or Modules

```
/* to check the creature model:
SELECT *
FROM creature_template_model
WHERE creatureid = 500030 
OR creatureid = 500031 
OR creatureid = 500032 
*/
/* to add the missing model for the creatures
INSERT INTO creature_template_model (CreatureID, IDX, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(500030,0,25901,1,1,1)

INSERT INTO creature_template_model (CreatureID, IDX, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES 
(500031,0,25901,1,1,1)

INSERT INTO creature_template_model (CreatureID, IDX, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(500032,0,18234,1,1,1)
*/```

**Comment by Nelnamara** [comment]
A PR has already been submitted to update the SQL queries.  

A change to the core this month removed the model data from creature_template and added it to a new SQL table.  I have updated the code and it is pending testing and approval.

https://github.com/azerothcore/mod-guildhouse/pull/49

**Comment by bblrlo** [comment]
> A PR has already been submitted to update the SQL queries.
> 
> A change to the core this month removed the model data from creature_template and added it to a new SQL table. I have updated the code and it is pending testing and approval.
> 
> #51

It works

**Comment by samunit** [comment]
> A PR has already been submitted to update the SQL queries.
> 
> A change to the core this month removed the model data from creature_template and added it to a new SQL table. I have updated the code and it is pending testing and approval.
> 
> #51

This saved me :) Thanks
