### ISSUE TITLE
Bug: Creature (Entry: 500030) has no model defined in table `creature_template_model`, can't load.

### ISSUE THREAD

**Issue by xengine-qyt** [azerothcore/mod-guildhouse#56]
### Current Behaviour

.npc add 500030
![image](https://github.com/user-attachments/assets/4596581b-1636-498c-9d16-e69d0231bb72)

and worldserver print:Creature (Entry: 500030) has no model defined in table `creature_template_model`, can't load.

### Expected Behaviour

create npc

### Steps to reproduce the problem

.npc add 500030

### AC rev. hash/commit

tody last version

### Operating system

ubuntu24

**Comment by mingjiansi** [comment]
PR is an attempt to fix this issue.
https://github.com/azerothcore/mod-guildhouse/pull/57

**Comment by xengine-qyt** [comment]
thanks,why not merge?

**Comment by d-christ** [comment]
I tried the fix and created the table entries. When i now use ".npc add 500030" it just shows me the help for the npc command:

![image](https://github.com/user-attachments/assets/536b2db0-3aec-421b-a944-9826838836f7)
